### ISSUE TITLE
WP Settings?

### ISSUE THREAD

**Issue by djmtype** [deviodigital/modaal-wordpress-plugin#1]
This project maybe abandoned, but I was wondering if there was any settings for this plugin. There's nothing I see within the admin under Settings or Media to enable the modal.

**Comment by robertdevore** [comment]
No, there isn't . If you're looking or a good starting point for WordPress settings, check out [WP-OOP-Settings-API](https://github.com/ahmadawais/WP-OOP-Settings-API) from @ahmadawais :+1:
